version: '3.8'

services:

  1_shepherd:
    container_name: 1_shepherd
    command: python main.py
    depends_on:
      - 3_db
    networks:
      - tc

  2_load_data:
    container_name: 2_load_data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    depends_on:
      - 3_db
    networks:
      - tc

  3_db:
    image: postgres:15-alpine
    container_name: 3_db
    ports:
      - "5434:5432"
    networks:
      - tc

  4_mlflow:
    container_name: 4_mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports:
      - "5001:5000"
    depends_on:
      - 3_db
    networks:
      - tc

  4_api:
    container_name: 4_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8002:8000"
    depends_on:
      - 3_db
    networks:
      - tc

  4_prometheus:
    image: prom/prometheus:latest
    container_name: 4_prometheus
    ports:
      - "9090:9090"
    depends_on:
      - 3_db
      - 4_api
    networks:
      - tc

  5_metrics:
    container_name: 5_metrics
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8003:8000"
    depends_on:
      - 3_db
    networks:
      - tc

networks:
  tc:
    driver: bridge