version: '3.8'

services:

  1_shepherd:
    container_name: 1_shepherd
    image: 1_shepherd:latest
    depends_on:
      - 3_db
    networks:
      - tc

  2_load_data:
    container_name: 2_load_data
    image: 2_load_data:latest
    ports:
      - "8001:8000"
    depends_on:
      - 3_db
    networks:
      - tc

  3_db:
    image: 3_db:latest
    container_name: 3_db
    ports:
      - "5434:5432"
    networks:
      - tc

  4_mlflow:
    container_name: 4_mlflow
    image: 3_nn_mlflow:latest
    ports:
      - "5001:5000"
    depends_on:
      - 3_db
    networks:
      - tc

  4_api:
    container_name: 4_api
    image: 3_nn_api:latest
    ports:
      - "8002:8000"
    depends_on:
      - 3_db
    networks:
      - tc

  4_prometheus:
    image: 3_nn_prometheus:latest
    container_name: 4_prometheus
    ports:
      - "9090:9090"
    depends_on:
      - 3_db
      - 4_api
    networks:
      - tc

  5_metrics:
    container_name: 5_metrics
    image: 5_metrics:latest
    ports:
      - "8003:8000"
    depends_on:
      - 3_db
    networks:
      - tc

networks:
  tc:
    driver: bridge